# Generated by Django 4.2 on 2023-06-07 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=500)),
                ('picture', models.ImageField(upload_to='')),
                ('health', models.IntegerField()),
                ('loot', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('pattern', models.CharField(max_length=500)),
                ('Enemy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protoWiki11.enemy')),
            ],
        ),
    ]
