# Generated by Django 4.2 on 2023-06-07 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protoWiki11', '0002_enemy_runes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=500)),
                ('picture', models.ImageField(upload_to='')),
                ('description', models.CharField(max_length=500)),
                ('cost', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='NPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=500)),
                ('picture', models.ImageField(upload_to='')),
                ('description', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='boss',
            name='pattern',
            field=models.CharField(max_length=800),
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage_types', models.CharField(max_length=500)),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protoWiki11.item')),
            ],
        ),
    ]
