# Generated by Django 4.2 on 2023-06-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protoWiki11', '0003_item_npc_alter_boss_pattern_weapon'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='location',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weapon',
            name='skill',
            field=models.CharField(default=2, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='cost',
            field=models.CharField(max_length=120),
        ),
    ]
